### ISSUE TITLE
29.9. Peer review

### ISSUE THREAD

**Issue by mikkoisa** [Mtk112/CaloriesWatcher#14]
- Text fields should allow only numbers in number-fields
- In text field input enter could jump to next field or hide keyboard when in last field
- When button to save data has been pressed, the input fields could be cleared
- Visual indicators when a action is triggered (e.g when save button is pressed and data saved)
- Back button on top bar or somewhere 

Review by:
Mikko Saarinen, Simo Pessi

**Comment by Mtk112** [comment]
Number fields fixed. Including hiding keyboard.
Problems with hiding keyboard when input is text.
Visual indicators fixed with toasts.
Back button done.

**Comment by Mtk112** [comment]
Fixed issue with keyboard not closing when inputting text.

-done
